package View;

import Controller.Controller_Dashboard;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Agung Nursatria
 */
public class Absen extends javax.swing.JFrame {

    /**
     * Creates new form Absen
     */
    public Absen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupstatus = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJam = new javax.swing.JTextField();
        txtMenit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBulan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RButMasuk = new javax.swing.JRadioButton();
        RButKeluar = new javax.swing.JRadioButton();
        btnSubmitAbsen = new javax.swing.JPanel();
        jbtnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 143, 195, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Absen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 33, 115, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Waktu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 174, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(":");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 173, -1, -1));

        txtJam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJam.setText("Jam");
        txtJam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJamMouseClicked(evt);
            }
        });
        jPanel1.add(txtJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 171, 39, -1));

        txtMenit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMenit.setText("Menit");
        txtMenit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMenitMouseClicked(evt);
            }
        });
        jPanel1.add(txtMenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 171, 40, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 226, -1, -1));

        txtHari.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHari.setText("DD");
        txtHari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHariMouseClicked(evt);
            }
        });
        jPanel1.add(txtHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 223, 34, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("-");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 226, -1, -1));

        txtBulan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBulan.setText("MM");
        txtBulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBulanMouseClicked(evt);
            }
        });
        jPanel1.add(txtBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 223, 34, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 218, -1, 31));

        txtTahun.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTahun.setText("YYYY");
        txtTahun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTahunMouseClicked(evt);
            }
        });
        jPanel1.add(txtTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 223, 47, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 277, -1, -1));

        RButMasuk.setBackground(jPanel1.getBackground());
        btnGroupstatus.add(RButMasuk);
        RButMasuk.setForeground(new java.awt.Color(255, 255, 255));
        RButMasuk.setSelected(true);
        RButMasuk.setText("Masuk");
        jPanel1.add(RButMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 273, -1, -1));

        RButKeluar.setBackground(jPanel1.getBackground());
        btnGroupstatus.add(RButKeluar);
        RButKeluar.setForeground(new java.awt.Color(255, 255, 255));
        RButKeluar.setText("Keluar");
        jPanel1.add(RButKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 273, -1, -1));

        btnSubmitAbsen.setBackground(new java.awt.Color(0, 134, 112));
        btnSubmitAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitAbsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitAbsenMouseExited(evt);
            }
        });

        jbtnSubmit.setBackground(btnSubmitAbsen.getBackground());
        jbtnSubmit.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jbtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSubmit.setText("Submit");
        jbtnSubmit.setBorderPainted(false);
        jbtnSubmit.setContentAreaFilled(false);
        jbtnSubmit.setFocusPainted(false);
        jbtnSubmit.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jbtnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnSubmitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSubmitAbsenLayout = new javax.swing.GroupLayout(btnSubmitAbsen);
        btnSubmitAbsen.setLayout(btnSubmitAbsenLayout);
        btnSubmitAbsenLayout.setHorizontalGroup(
            btnSubmitAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        btnSubmitAbsenLayout.setVerticalGroup(
            btnSubmitAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnSubmitAbsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 329, -1, 30));

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 306, -1));

        txtId.setBackground(jPanel1.getBackground());
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("ID");
        txtId.setBorder(null);
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 123, 115, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(306, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        txtId.setText("");
    }//GEN-LAST:event_txtIdMouseClicked

    private void txtTahunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTahunMouseClicked
        txtTahun.setText("");
    }//GEN-LAST:event_txtTahunMouseClicked

    private void txtBulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBulanMouseClicked
        txtBulan.setText("");
    }//GEN-LAST:event_txtBulanMouseClicked

    private void txtHariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHariMouseClicked
        txtHari.setText("");
    }//GEN-LAST:event_txtHariMouseClicked

    private void txtMenitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenitMouseClicked
        txtMenit.setText("");
    }//GEN-LAST:event_txtMenitMouseClicked

    private void txtJamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJamMouseClicked
        txtJam.setText("");
    }//GEN-LAST:event_txtJamMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        dispose();
        new Controller_Dashboard();
    }//GEN-LAST:event_exitMouseClicked

    private void btnSubmitAbsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitAbsenMouseExited
        btnSubmitAbsen.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnSubmitAbsenMouseExited

    private void btnSubmitAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitAbsenMouseEntered
        btnSubmitAbsen.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnSubmitAbsenMouseEntered

    private void jbtnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSubmitMouseEntered
        btnSubmitAbsen.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jbtnSubmitMouseEntered

    private void jbtnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSubmitMouseExited
        btnSubmitAbsen.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jbtnSubmitMouseExited

    /**
     * @param args the command line arguments
     */

    public JRadioButton getRButKeluar() {
        return RButKeluar;
    }

    public JRadioButton getRButMasuk() {
        return RButMasuk;
    }

    public ButtonGroup getBtnGroupstatus() {
        return btnGroupstatus;
    }

    public JPanel getBtnSubmitAbsen() {
        return btnSubmitAbsen;
    }

    public JButton getJbtnSubmit() {
        return jbtnSubmit;
    }

    public JTextField getTxtBulan() {
        return txtBulan;
    }

    public JTextField getTxtHari() {
        return txtHari;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtJam() {
        return txtJam;
    }

    public JTextField getTxtMenit() {
        return txtMenit;
    }

    public JTextField getTxtTahun() {
        return txtTahun;
    }

    public void Reset(){
        txtBulan.setText("Bulan");
        txtHari.setText("Hari");
        txtId.setText("ID");
        txtJam.setText("Jam");
        txtMenit.setText("Menit");
        txtTahun.setText("Tahun");
        RButMasuk.setSelected(true);
        RButKeluar.setSelected(false);
        
    }

    public void addActionListener(ActionListener e){
        jbtnSubmit.addActionListener(e);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absen().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RButKeluar;
    private javax.swing.JRadioButton RButMasuk;
    private javax.swing.ButtonGroup btnGroupstatus;
    private javax.swing.JPanel btnSubmitAbsen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextField txtHari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtMenit;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
