/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Agung Nursatria
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAbsensi = new javax.swing.JPanel();
        jBtnAbsen = new javax.swing.JButton();
        btnInfo = new javax.swing.JPanel();
        jBtnInfo = new javax.swing.JButton();
        btnLogin = new javax.swing.JPanel();
        jBtnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        jLabel3.setAlignmentY(0.0F);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 374, 291, -1));

        jPanel3.setBackground(new java.awt.Color(217, 14, 14));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 34, 156, -1));

        btnAbsensi.setBackground(new java.awt.Color(0, 134, 112));
        btnAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbsensiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbsensiMouseExited(evt);
            }
        });

        jBtnAbsen.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jBtnAbsen.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAbsen.setText("Absen");
        jBtnAbsen.setBorderPainted(false);
        jBtnAbsen.setContentAreaFilled(false);
        jBtnAbsen.setFocusPainted(false);
        jBtnAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnAbsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAbsenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAbsensiLayout = new javax.swing.GroupLayout(btnAbsensi);
        btnAbsensi.setLayout(btnAbsensiLayout);
        btnAbsensiLayout.setHorizontalGroup(
            btnAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnAbsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAbsensiLayout.setVerticalGroup(
            btnAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAbsensiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnAbsen))
        );

        jPanel1.add(btnAbsensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 147, 140, 30));

        btnInfo.setBackground(new java.awt.Color(0, 134, 112));
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
        });

        jBtnInfo.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnInfo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnInfo.setText("INFO");
        jBtnInfo.setBorderPainted(false);
        jBtnInfo.setContentAreaFilled(false);
        jBtnInfo.setFocusPainted(false);
        jBtnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnInfoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnInfoLayout = new javax.swing.GroupLayout(btnInfo);
        btnInfo.setLayout(btnInfoLayout);
        btnInfoLayout.setHorizontalGroup(
            btnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInfoLayout.createSequentialGroup()
                .addComponent(jBtnInfo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnInfoLayout.setVerticalGroup(
            btnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 337, 60, 20));

        btnLogin.setBackground(new java.awt.Color(0, 134, 112));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        jBtnLogin.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogin.setText("Login");
        jBtnLogin.setBorderPainted(false);
        jBtnLogin.setContentAreaFilled(false);
        jBtnLogin.setFocusPainted(false);
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnLogin))
        );

        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 225, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("APASI TOR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 47));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(291, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnAbsensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbsensiMouseEntered
        btnAbsensi.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnAbsensiMouseEntered

    private void btnAbsensiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbsensiMouseExited
        btnAbsensi.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnAbsensiMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited
        btnInfo.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnInfoMouseExited

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered
        btnInfo.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnInfoMouseEntered

    private void jBtnAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAbsenMouseEntered
        // TODO add your handling code here:
        btnAbsensi.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnAbsenMouseEntered

    private void jBtnAbsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAbsenMouseExited
        // TODO add your handling code here:
        btnAbsensi.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnAbsenMouseExited

    private void jBtnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInfoMouseExited
        // TODO add your handling code here:
        btnInfo.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnInfoMouseExited

    private void jBtnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInfoMouseEntered
        // TODO add your handling code here:
        btnInfo.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnInfoMouseEntered

    private void jBtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnLoginMouseExited

    private void jBtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnLoginMouseEntered

    public JPanel getBtnAbsensi() {
        return btnAbsensi;
    }

    public void setBtnAbsensi(JPanel btnAbsensi) {
        this.btnAbsensi = btnAbsensi;
    }

    public JPanel getBtnInfo() {
        return btnInfo;
    }

    public JPanel getBtnLogin() {
        return btnLogin;
    }

    public JButton getjBtnAbsen() {
        return jBtnAbsen;
    }

    public JButton getjBtnInfo() {
        return jBtnInfo;
    }

    public JButton getjBtnLogin() {
        return jBtnLogin;
    }

    public void setjBtnLogin(JButton jBtnLogin) {
        this.jBtnLogin = jBtnLogin;
    }

    
    public void addActionListener(ActionListener e){
        jBtnInfo.addActionListener(e);
        jBtnAbsen.addActionListener(e);
        jBtnLogin.addActionListener(e);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAbsensi;
    private javax.swing.JPanel btnInfo;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jBtnAbsen;
    private javax.swing.JButton jBtnInfo;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
