/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JTextField;

/**
 *
 * @author Agung Nursatria
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        txtJumlahPegawai = new javax.swing.JTextField();
        txtNamaPerusahaan = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtKontak = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 306, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        txtJumlahPegawai.setEditable(false);
        txtJumlahPegawai.setBackground(jPanel1.getBackground());
        txtJumlahPegawai.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtJumlahPegawai.setForeground(new java.awt.Color(255, 255, 255));
        txtJumlahPegawai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJumlahPegawai.setText("{ Jumlah Pegawai }");
        txtJumlahPegawai.setBorder(null);
        txtJumlahPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtJumlahPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 190, -1));

        txtNamaPerusahaan.setEditable(false);
        txtNamaPerusahaan.setBackground(jPanel1.getBackground());
        txtNamaPerusahaan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNamaPerusahaan.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaPerusahaan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamaPerusahaan.setText("{ Perusahaan }");
        txtNamaPerusahaan.setBorder(null);
        txtNamaPerusahaan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtNamaPerusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 190, -1));

        txtAlamat.setEditable(false);
        txtAlamat.setBackground(jPanel1.getBackground());
        txtAlamat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlamat.setText("{ Alamat }");
        txtAlamat.setBorder(null);
        txtAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 190, -1));

        txtKontak.setEditable(false);
        txtKontak.setBackground(jPanel1.getBackground());
        txtKontak.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtKontak.setForeground(new java.awt.Color(255, 255, 255));
        txtKontak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKontak.setText("{ Kontak }");
        txtKontak.setBorder(null);
        txtKontak.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtKontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 190, -1));

        jPanel3.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 306, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_exitMouseClicked

    
    public void set(String Nama,String alamat,String kontak,int jumlah){
        txtNamaPerusahaan.setText(Nama);
        txtAlamat.setText(alamat);
        txtKontak.setText(kontak);
        txtJumlahPegawai.setText("Total Pegawai : " + jumlah);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtJumlahPegawai;
    private javax.swing.JTextField txtKontak;
    private javax.swing.JTextField txtNamaPerusahaan;
    // End of variables declaration//GEN-END:variables
}
