/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Agung Nursatria
 */
public class MenuPegawaiHonorer extends javax.swing.JFrame {

    /**
     * Creates new form MenuPegawaiHonorer
     */
    public MenuPegawaiHonorer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        btnUbahDataDiri = new javax.swing.JPanel();
        jBtnUbahDataD = new javax.swing.JButton();
        btnUbahPassword = new javax.swing.JPanel();
        jBtnUbahP = new javax.swing.JButton();
        btnLogOut = new javax.swing.JPanel();
        jBtnLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtUmur = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtJenisK = new javax.swing.JTextField();
        txtHonor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listdaftarabsen = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isiDataAbsen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Menu Pegawai Honorer");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 45, -1, -1));

        btnUbahDataDiri.setBackground(new java.awt.Color(0, 134, 112));
        btnUbahDataDiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahDataDiriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahDataDiriMouseExited(evt);
            }
        });

        jBtnUbahDataD.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnUbahDataD.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUbahDataD.setText("Ubah Data Diri");
        jBtnUbahDataD.setBorderPainted(false);
        jBtnUbahDataD.setContentAreaFilled(false);
        jBtnUbahDataD.setFocusPainted(false);
        jBtnUbahDataD.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnUbahDataD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnUbahDataDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnUbahDataDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUbahDataDiriLayout = new javax.swing.GroupLayout(btnUbahDataDiri);
        btnUbahDataDiri.setLayout(btnUbahDataDiriLayout);
        btnUbahDataDiriLayout.setHorizontalGroup(
            btnUbahDataDiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUbahDataDiriLayout.createSequentialGroup()
                .addComponent(jBtnUbahDataD, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        btnUbahDataDiriLayout.setVerticalGroup(
            btnUbahDataDiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnUbahDataD, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnUbahDataDiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 80, 127, -1));

        btnUbahPassword.setBackground(new java.awt.Color(0, 134, 112));
        btnUbahPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseExited(evt);
            }
        });

        jBtnUbahP.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnUbahP.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUbahP.setText("Ubah Password");
        jBtnUbahP.setBorderPainted(false);
        jBtnUbahP.setContentAreaFilled(false);
        jBtnUbahP.setFocusPainted(false);
        jBtnUbahP.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnUbahP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnUbahPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnUbahPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUbahPasswordLayout = new javax.swing.GroupLayout(btnUbahPassword);
        btnUbahPassword.setLayout(btnUbahPasswordLayout);
        btnUbahPasswordLayout.setHorizontalGroup(
            btnUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUbahPasswordLayout.createSequentialGroup()
                .addComponent(jBtnUbahP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        btnUbahPasswordLayout.setVerticalGroup(
            btnUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnUbahP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnUbahPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 127, -1));

        btnLogOut.setBackground(new java.awt.Color(0, 134, 112));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });

        jBtnLogOut.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogOut.setText("Log Out");
        jBtnLogOut.setBorderPainted(false);
        jBtnLogOut.setContentAreaFilled(false);
        jBtnLogOut.setFocusPainted(false);
        jBtnLogOut.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLogOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLogOutLayout = new javax.swing.GroupLayout(btnLogOut);
        btnLogOut.setLayout(btnLogOutLayout);
        btnLogOutLayout.setHorizontalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogOutLayout.createSequentialGroup()
                .addComponent(jBtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        btnLogOutLayout.setVerticalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 127, -1));

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 472, -1, -1));

        txtNama.setEditable(false);
        txtNama.setBackground(jPanel1.getBackground());
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Nama");
        txtNama.setBorder(null);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 115, -1));

        txtId.setEditable(false);
        txtId.setBackground(jPanel1.getBackground());
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("Id");
        txtId.setBorder(null);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 115, -1));

        txtUmur.setEditable(false);
        txtUmur.setBackground(jPanel1.getBackground());
        txtUmur.setForeground(new java.awt.Color(255, 255, 255));
        txtUmur.setText("Umur");
        txtUmur.setBorder(null);
        jPanel1.add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 115, -1));

        txtAlamat.setEditable(false);
        txtAlamat.setBackground(jPanel1.getBackground());
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setText("Alamat");
        txtAlamat.setBorder(null);
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 115, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(jPanel1.getBackground());
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 115, -1));

        txtJenisK.setEditable(false);
        txtJenisK.setBackground(jPanel1.getBackground());
        txtJenisK.setForeground(new java.awt.Color(255, 255, 255));
        txtJenisK.setText("Jenis-Kelamin");
        txtJenisK.setBorder(null);
        jPanel1.add(txtJenisK, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 115, -1));

        txtHonor.setEditable(false);
        txtHonor.setBackground(jPanel1.getBackground());
        txtHonor.setForeground(new java.awt.Color(255, 255, 255));
        txtHonor.setText("Honor");
        txtHonor.setBorder(null);
        jPanel1.add(txtHonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 115, -1));

        listdaftarabsen.setBackground(new java.awt.Color(10, 31, 31));
        listdaftarabsen.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listdaftarabsen);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 190));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email  :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Honor :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Umur  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Absensi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID      :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alamat :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        isiDataAbsen.setEditable(false);
        isiDataAbsen.setBackground(new java.awt.Color(10, 31, 31));
        isiDataAbsen.setColumns(20);
        isiDataAbsen.setRows(5);
        jScrollPane1.setViewportView(isiDataAbsen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 230, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void btnUbahDataDiriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahDataDiriMouseEntered
        btnUbahDataDiri.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnUbahDataDiriMouseEntered

    private void btnUbahDataDiriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahDataDiriMouseExited
        btnUbahDataDiri.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnUbahDataDiriMouseExited

    private void btnUbahPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseEntered
        btnUbahPassword.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnUbahPasswordMouseEntered

    private void btnUbahPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseExited
        btnUbahPassword.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnUbahPasswordMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        btnLogOut.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        btnLogOut.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnLogOutMouseExited

    private void jBtnUbahDataDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahDataDMouseEntered
        // TODO add your handling code here:
        btnUbahDataDiri.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnUbahDataDMouseEntered

    private void jBtnUbahDataDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahDataDMouseExited
        // TODO add your handling code here:
        btnUbahDataDiri.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnUbahDataDMouseExited

    private void jBtnUbahPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahPMouseEntered
        // TODO add your handling code here:
        btnUbahPassword.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnUbahPMouseEntered

    private void jBtnUbahPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahPMouseExited
        // TODO add your handling code here:
        btnUbahPassword.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnUbahPMouseExited

    private void jBtnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogOutMouseEntered
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnLogOutMouseEntered

    private void jBtnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogOutMouseExited
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnLogOutMouseExited

    public JButton getjBtnUbahDataD() {
        return jBtnUbahDataD;
    }

    public JButton getjBtnLogOut() {
        return jBtnLogOut;
    }

    public JButton getjBtnUbahP() {
        return jBtnUbahP;
    }

    public JList<String> getjList2() {
        return listdaftarabsen;
    }

    public JTextArea getIsiDataAbsen() {
        return isiDataAbsen;
    }

    public JList<String> getListdaftarabsen() {
        return listdaftarabsen;
    }

    
    public JTextField getTxtAlamat() {
        return txtAlamat;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtHonor() {
        return txtHonor;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtJenisK() {
        return txtJenisK;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtUmur() {
        return txtUmur;
    }

    
    public void Reset(){
        isiDataAbsen.removeAll();
        listdaftarabsen.removeAll();
    }

    public void addActionListener(ActionListener e){
        jBtnUbahDataD.addActionListener(e);
        jBtnLogOut.addActionListener(e);
        jBtnUbahP.addActionListener(e);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiHonorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiHonorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiHonorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiHonorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPegawaiHonorer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnUbahDataDiri;
    private javax.swing.JPanel btnUbahPassword;
    private javax.swing.JLabel exit;
    private javax.swing.JTextArea isiDataAbsen;
    private javax.swing.JButton jBtnLogOut;
    private javax.swing.JButton jBtnUbahDataD;
    private javax.swing.JButton jBtnUbahP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JList<String> listdaftarabsen;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHonor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJenisK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
