/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Agung Nursatria
 */
public class MenuPegawaiTetap extends javax.swing.JFrame {

    /**
     * Creates new form MenuPegawaiTetap
     */
    public MenuPegawaiTetap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        btnUbahDataDiri = new javax.swing.JPanel();
        jBtnUbahDataD = new javax.swing.JButton();
        btnUbahPassword = new javax.swing.JPanel();
        jBtnUbahP = new javax.swing.JButton();
        btnLogOut = new javax.swing.JPanel();
        jBtnLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtUmur = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtJenisK = new javax.swing.JTextField();
        txtHonor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        listdaftarabsen = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnTambahT = new javax.swing.JPanel();
        jBtnTambahT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        isiDataAbsen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Menu Pegawai Honorer");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 45, -1, -1));

        btnUbahDataDiri.setBackground(new java.awt.Color(0, 134, 112));
        btnUbahDataDiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahDataDiriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahDataDiriMouseExited(evt);
            }
        });

        jBtnUbahDataD.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnUbahDataD.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUbahDataD.setText("Ubah Data Diri");
        jBtnUbahDataD.setBorderPainted(false);
        jBtnUbahDataD.setContentAreaFilled(false);
        jBtnUbahDataD.setFocusPainted(false);
        jBtnUbahDataD.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnUbahDataD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnUbahDataDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnUbahDataDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUbahDataDiriLayout = new javax.swing.GroupLayout(btnUbahDataDiri);
        btnUbahDataDiri.setLayout(btnUbahDataDiriLayout);
        btnUbahDataDiriLayout.setHorizontalGroup(
            btnUbahDataDiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUbahDataDiriLayout.createSequentialGroup()
                .addComponent(jBtnUbahDataD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        btnUbahDataDiriLayout.setVerticalGroup(
            btnUbahDataDiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnUbahDataD, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnUbahDataDiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 127, -1));

        btnUbahPassword.setBackground(new java.awt.Color(0, 134, 112));
        btnUbahPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseExited(evt);
            }
        });

        jBtnUbahP.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnUbahP.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUbahP.setText("Ubah Password");
        jBtnUbahP.setBorderPainted(false);
        jBtnUbahP.setContentAreaFilled(false);
        jBtnUbahP.setFocusPainted(false);
        jBtnUbahP.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnUbahP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnUbahPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnUbahPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUbahPasswordLayout = new javax.swing.GroupLayout(btnUbahPassword);
        btnUbahPassword.setLayout(btnUbahPasswordLayout);
        btnUbahPasswordLayout.setHorizontalGroup(
            btnUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnUbahP, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        btnUbahPasswordLayout.setVerticalGroup(
            btnUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnUbahP, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnUbahPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 127, -1));

        btnLogOut.setBackground(new java.awt.Color(0, 134, 112));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });

        jBtnLogOut.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogOut.setText("Log Out");
        jBtnLogOut.setBorderPainted(false);
        jBtnLogOut.setContentAreaFilled(false);
        jBtnLogOut.setFocusPainted(false);
        jBtnLogOut.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLogOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLogOutLayout = new javax.swing.GroupLayout(btnLogOut);
        btnLogOut.setLayout(btnLogOutLayout);
        btnLogOutLayout.setHorizontalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        btnLogOutLayout.setVerticalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 127, -1));

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 472, 650, -1));

        txtNama.setEditable(false);
        txtNama.setBackground(jPanel1.getBackground());
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Nama");
        txtNama.setBorder(null);
        txtNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNamaMouseClicked(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 115, -1));

        txtId.setEditable(false);
        txtId.setBackground(jPanel1.getBackground());
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("Id");
        txtId.setBorder(null);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 115, -1));

        txtUmur.setEditable(false);
        txtUmur.setBackground(jPanel1.getBackground());
        txtUmur.setForeground(new java.awt.Color(255, 255, 255));
        txtUmur.setText("Umur");
        txtUmur.setBorder(null);
        txtUmur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUmurMouseClicked(evt);
            }
        });
        jPanel1.add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 115, -1));

        txtAlamat.setEditable(false);
        txtAlamat.setBackground(jPanel1.getBackground());
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setText("Alamat");
        txtAlamat.setBorder(null);
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 115, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(jPanel1.getBackground());
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 115, -1));

        txtJenisK.setEditable(false);
        txtJenisK.setBackground(jPanel1.getBackground());
        txtJenisK.setForeground(new java.awt.Color(255, 255, 255));
        txtJenisK.setText("Jenis-Kelamin");
        txtJenisK.setBorder(null);
        jPanel1.add(txtJenisK, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 115, -1));

        txtHonor.setEditable(false);
        txtHonor.setBackground(jPanel1.getBackground());
        txtHonor.setForeground(new java.awt.Color(255, 255, 255));
        txtHonor.setText("Honor");
        txtHonor.setBorder(null);
        jPanel1.add(txtHonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 115, -1));

        listdaftarabsen.setBackground(new java.awt.Color(10, 31, 31));
        listdaftarabsen.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(listdaftarabsen);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 190));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Honor :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nama :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Umur :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Absensi");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Jenis Kelamin : ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("ID      :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Alamat :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        btnTambahT.setBackground(new java.awt.Color(0, 134, 112));
        btnTambahT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahTMouseExited(evt);
            }
        });

        jBtnTambahT.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        jBtnTambahT.setForeground(new java.awt.Color(255, 255, 255));
        jBtnTambahT.setText("Tambah Tunjangan");
        jBtnTambahT.setBorderPainted(false);
        jBtnTambahT.setContentAreaFilled(false);
        jBtnTambahT.setFocusPainted(false);
        jBtnTambahT.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnTambahT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTambahTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTambahTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTambahTLayout = new javax.swing.GroupLayout(btnTambahT);
        btnTambahT.setLayout(btnTambahTLayout);
        btnTambahTLayout.setHorizontalGroup(
            btnTambahTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnTambahT, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        btnTambahTLayout.setVerticalGroup(
            btnTambahTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnTambahT, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnTambahT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 127, -1));

        isiDataAbsen.setEditable(false);
        isiDataAbsen.setBackground(new java.awt.Color(10, 31, 31));
        isiDataAbsen.setColumns(20);
        isiDataAbsen.setRows(5);
        jScrollPane1.setViewportView(isiDataAbsen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 230, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void btnUbahDataDiriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahDataDiriMouseEntered
        btnUbahDataDiri.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnUbahDataDiriMouseEntered

    private void btnUbahDataDiriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahDataDiriMouseExited
        btnUbahDataDiri.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnUbahDataDiriMouseExited

    private void btnUbahPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseEntered
        btnUbahPassword.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnUbahPasswordMouseEntered

    private void btnUbahPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseExited
        btnUbahPassword.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnUbahPasswordMouseExited

    private void txtNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaMouseClicked

    }//GEN-LAST:event_txtNamaMouseClicked

    private void txtUmurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUmurMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseClicked

    private void btnTambahTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahTMouseEntered

    private void btnTambahTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahTMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahTMouseExited

    private void jBtnUbahDataDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahDataDMouseEntered
        // TODO add your handling code here:
        btnUbahDataDiri.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnUbahDataDMouseEntered

    private void jBtnUbahDataDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahDataDMouseExited
        // TODO add your handling code here:
        btnUbahDataDiri.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnUbahDataDMouseExited

    private void jBtnUbahPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahPMouseEntered
        // TODO add your handling code here:
        btnUbahPassword.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnUbahPMouseEntered

    private void jBtnUbahPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUbahPMouseExited
        // TODO add your handling code here:
        btnUbahPassword.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnUbahPMouseExited

    private void jBtnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogOutMouseEntered
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnLogOutMouseEntered

    private void jBtnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogOutMouseExited
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnLogOutMouseExited

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        btnLogOut.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        btnLogOut.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void jBtnTambahTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTambahTMouseEntered
        // TODO add your handling code here:
        btnTambahT.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnTambahTMouseEntered

    private void jBtnTambahTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTambahTMouseExited
        // TODO add your handling code here:
        btnTambahT.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnTambahTMouseExited

    public JButton getjBtnUbahDataD() {
        return jBtnUbahDataD;
    }

    public JButton getjBtnLogOut() {
        return jBtnLogOut;
    }

    public JButton getjBtnUbahP() {
        return jBtnUbahP;
    }

    public JButton getjBtnTambahT() {
        return jBtnTambahT;
    }

    public JList<String> getjList4() {
        return listdaftarabsen;
    }

    public JTextArea getIsiDataAbsen() {
        return isiDataAbsen;
    }

    public JList<String> getListdaftarabsen() {
        return listdaftarabsen;
    }
    
    public JTextField getTxtAlamat() {
        return txtAlamat;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtHonor() {
        return txtHonor;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtJenisK() {
        return txtJenisK;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtUmur() {
        return txtUmur;
    }
    
    public void Reset(){
        listdaftarabsen.removeAll();
        isiDataAbsen.removeAll();
    }

    public void addActionListener(ActionListener e){
        jBtnUbahDataD.addActionListener(e);
        jBtnLogOut.addActionListener(e);
        jBtnUbahP.addActionListener(e);
        jBtnTambahT.addActionListener(e);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiTetap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiTetap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiTetap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPegawaiTetap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPegawaiTetap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnTambahT;
    private javax.swing.JPanel btnUbahDataDiri;
    private javax.swing.JPanel btnUbahPassword;
    private javax.swing.JLabel exit;
    private javax.swing.JTextArea isiDataAbsen;
    private javax.swing.JButton jBtnLogOut;
    private javax.swing.JButton jBtnTambahT;
    private javax.swing.JButton jBtnUbahDataD;
    private javax.swing.JButton jBtnUbahP;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private javax.swing.JList<String> listdaftarabsen;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHonor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJenisK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
