/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author Agung Nursatria
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ListDaftarPegawai
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        btnTambahPegawai = new javax.swing.JPanel();
        jbtnTambahP = new javax.swing.JButton();
        btnTambahDepartemen = new javax.swing.JPanel();
        jbtnTambahD = new javax.swing.JButton();
        btnHapusPegawai = new javax.swing.JPanel();
        jBtnHapusP = new javax.swing.JButton();
        btnLogOut = new javax.swing.JPanel();
        jBtnLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPegawai = new javax.swing.JList<>();
        label2 = new java.awt.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDepartemen = new javax.swing.JList<>();
        label3 = new java.awt.Label();
        btnEditPerusahaan = new javax.swing.JPanel();
        jbtnEditPerusahaan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        exit.setBackground(new java.awt.Color(0, 51, 51));

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Menu Admin");

        btnTambahPegawai.setBackground(new java.awt.Color(0, 134, 112));
        btnTambahPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahPegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahPegawaiMouseExited(evt);
            }
        });

        jbtnTambahP.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jbtnTambahP.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTambahP.setText("Tambah Pegawai");
        jbtnTambahP.setBorderPainted(false);
        jbtnTambahP.setContentAreaFilled(false);
        jbtnTambahP.setFocusPainted(false);
        jbtnTambahP.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jbtnTambahP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnTambahPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnTambahPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTambahPegawaiLayout = new javax.swing.GroupLayout(btnTambahPegawai);
        btnTambahPegawai.setLayout(btnTambahPegawaiLayout);
        btnTambahPegawaiLayout.setHorizontalGroup(
            btnTambahPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTambahPegawaiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnTambahP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnTambahPegawaiLayout.setVerticalGroup(
            btnTambahPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnTambahP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnTambahDepartemen.setBackground(new java.awt.Color(0, 134, 112));
        btnTambahDepartemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahDepartemenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahDepartemenMouseExited(evt);
            }
        });

        jbtnTambahD.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jbtnTambahD.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTambahD.setText("Tambah Departemen");
        jbtnTambahD.setBorderPainted(false);
        jbtnTambahD.setContentAreaFilled(false);
        jbtnTambahD.setFocusPainted(false);
        jbtnTambahD.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jbtnTambahD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnTambahDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnTambahDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTambahDepartemenLayout = new javax.swing.GroupLayout(btnTambahDepartemen);
        btnTambahDepartemen.setLayout(btnTambahDepartemenLayout);
        btnTambahDepartemenLayout.setHorizontalGroup(
            btnTambahDepartemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTambahDepartemenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnTambahD, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnTambahDepartemenLayout.setVerticalGroup(
            btnTambahDepartemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnTambahD, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnHapusPegawai.setBackground(new java.awt.Color(0, 134, 112));
        btnHapusPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusPegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusPegawaiMouseExited(evt);
            }
        });

        jBtnHapusP.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnHapusP.setForeground(new java.awt.Color(255, 255, 255));
        jBtnHapusP.setText("Hapus Pegawai");
        jBtnHapusP.setBorderPainted(false);
        jBtnHapusP.setContentAreaFilled(false);
        jBtnHapusP.setFocusPainted(false);
        jBtnHapusP.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnHapusP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHapusPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHapusPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHapusPegawaiLayout = new javax.swing.GroupLayout(btnHapusPegawai);
        btnHapusPegawai.setLayout(btnHapusPegawaiLayout);
        btnHapusPegawaiLayout.setHorizontalGroup(
            btnHapusPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHapusPegawaiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnHapusP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnHapusPegawaiLayout.setVerticalGroup(
            btnHapusPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnHapusP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnLogOut.setBackground(new java.awt.Color(0, 134, 112));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });

        jBtnLogOut.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jBtnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogOut.setText("Log Out");
        jBtnLogOut.setBorderPainted(false);
        jBtnLogOut.setContentAreaFilled(false);
        jBtnLogOut.setFocusPainted(false);
        jBtnLogOut.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jBtnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLogOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLogOutLayout = new javax.swing.GroupLayout(btnLogOut);
        btnLogOut.setLayout(btnLogOutLayout);
        btnLogOutLayout.setHorizontalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogOutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnLogOutLayout.setVerticalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jListPegawai.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListPegawai);

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("List Daftar Pegawai");

        jListDepartemen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListDepartemen);

        label3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("List Departmen");

        btnEditPerusahaan.setBackground(new java.awt.Color(0, 134, 112));
        btnEditPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditPerusahaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditPerusahaanMouseExited(evt);
            }
        });

        jbtnEditPerusahaan.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jbtnEditPerusahaan.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEditPerusahaan.setText("  Edit Perusahaan");
        jbtnEditPerusahaan.setBorderPainted(false);
        jbtnEditPerusahaan.setContentAreaFilled(false);
        jbtnEditPerusahaan.setFocusPainted(false);
        jbtnEditPerusahaan.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jbtnEditPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnEditPerusahaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnEditPerusahaanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEditPerusahaanLayout = new javax.swing.GroupLayout(btnEditPerusahaan);
        btnEditPerusahaan.setLayout(btnEditPerusahaanLayout);
        btnEditPerusahaanLayout.setHorizontalGroup(
            btnEditPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditPerusahaanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnEditPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnEditPerusahaanLayout.setVerticalGroup(
            btnEditPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnEditPerusahaan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(exitLayout.createSequentialGroup()
                .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, exitLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(exitLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnEditPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, exitLayout.createSequentialGroup()
                        .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, exitLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTambahDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, exitLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(exitLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(exitLayout.createSequentialGroup()
                        .addComponent(btnTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnTambahPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahPegawaiMouseEntered
        btnTambahPegawai.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnTambahPegawaiMouseEntered

    private void btnTambahPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahPegawaiMouseExited
        btnTambahPegawai.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnTambahPegawaiMouseExited

    private void btnTambahDepartemenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDepartemenMouseEntered
        btnTambahDepartemen.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnTambahDepartemenMouseEntered

    private void btnTambahDepartemenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDepartemenMouseExited
        btnTambahDepartemen.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnTambahDepartemenMouseExited

    private void btnHapusPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusPegawaiMouseEntered

        btnHapusPegawai.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnHapusPegawaiMouseEntered

    private void btnHapusPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusPegawaiMouseExited
        btnHapusPegawai.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnHapusPegawaiMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        btnLogOut.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        btnLogOut.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnLogOutMouseExited

    private void jbtnTambahPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTambahPMouseEntered
        btnTambahPegawai.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jbtnTambahPMouseEntered

    private void jbtnTambahPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTambahPMouseExited
        btnTambahPegawai.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jbtnTambahPMouseExited

    private void jbtnTambahDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTambahDMouseEntered
        // TODO add your handling code here:
        btnTambahDepartemen.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jbtnTambahDMouseEntered

    private void jbtnTambahDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTambahDMouseExited
        // TODO add your handling code here:
        btnTambahDepartemen.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jbtnTambahDMouseExited

    private void jBtnHapusPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHapusPMouseEntered
        // TODO add your handling code here:
        btnHapusPegawai.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnHapusPMouseEntered

    private void jBtnHapusPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHapusPMouseExited
        // TODO add your handling code here:
        btnHapusPegawai.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnHapusPMouseExited

    private void jBtnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogOutMouseEntered
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jBtnLogOutMouseEntered

    private void jBtnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogOutMouseExited
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jBtnLogOutMouseExited

    private void jbtnEditPerusahaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditPerusahaanMouseEntered
        // TODO add your handling code here:
        btnEditPerusahaan.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jbtnEditPerusahaanMouseEntered

    private void jbtnEditPerusahaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditPerusahaanMouseExited
        // TODO add your handling code here:
        btnEditPerusahaan.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jbtnEditPerusahaanMouseExited

    private void btnEditPerusahaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPerusahaanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditPerusahaanMouseEntered

    private void btnEditPerusahaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPerusahaanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditPerusahaanMouseExited

    public JButton getJbtnEditPerusahaan() {
        return jbtnEditPerusahaan;
    }

    public JButton getjBtnHapusP() {
        return jBtnHapusP;
    }

    public JButton getjBtnLogOut() {
        return jBtnLogOut;
    }

    public JList<String> getjListDepartemen() {
        return jListDepartemen;
    }

    public JList<String> getjListPegawai() {
        return jListPegawai;
    }

    public JList<String> getjList1() {
        return jListPegawai;
    }


    public JList<String> getjList3() {
        return jListDepartemen;
    }


    public JButton getJbtnTambahD() {
        return jbtnTambahD;
    }


    public JButton getJbtnTambahP() {
        return jbtnTambahP;
    }


    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }


    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    
    public void Reset(){
        jListPegawai.removeAll();
        jListDepartemen.removeAll();
    }

    public void addActionListener(ActionListener e){
        jbtnEditPerusahaan.addActionListener(e);
        jBtnHapusP.addActionListener(e);
        jBtnLogOut.addActionListener(e);
        jbtnTambahD.addActionListener(e);
        jbtnTambahP.addActionListener(e);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEditPerusahaan;
    private javax.swing.JPanel btnHapusPegawai;
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnTambahDepartemen;
    private javax.swing.JPanel btnTambahPegawai;
    private javax.swing.JPanel exit;
    private javax.swing.JButton jBtnHapusP;
    private javax.swing.JButton jBtnLogOut;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListDepartemen;
    private javax.swing.JList<String> jListPegawai;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnEditPerusahaan;
    private javax.swing.JButton jbtnTambahD;
    private javax.swing.JButton jbtnTambahP;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
