/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Agung Nursatria
 */
public class TambahPegawai extends javax.swing.JFrame {

    /**
     * Creates new form TambahPegawai
     */
    public TambahPegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Status = new javax.swing.ButtonGroup();
        JenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnSubmitRegister = new javax.swing.JPanel();
        jbtnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtNama = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        RButTetap = new javax.swing.JRadioButton();
        RButHonorer = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        RButPerempuan = new javax.swing.JRadioButton();
        RButLaki = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnSubmitRegister.setBackground(new java.awt.Color(0, 134, 112));
        btnSubmitRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitRegisterMouseExited(evt);
            }
        });

        jbtnSubmit.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jbtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSubmit.setText("Submit");
        jbtnSubmit.setBorderPainted(false);
        jbtnSubmit.setContentAreaFilled(false);
        jbtnSubmit.setFocusPainted(false);
        jbtnSubmit.setMargin(new java.awt.Insets(0, 10, 2, 14));
        jbtnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnSubmitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSubmitRegisterLayout = new javax.swing.GroupLayout(btnSubmitRegister);
        btnSubmitRegister.setLayout(btnSubmitRegisterLayout);
        btnSubmitRegisterLayout.setHorizontalGroup(
            btnSubmitRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        btnSubmitRegisterLayout.setVerticalGroup(
            btnSubmitRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnSubmitRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 399, -1, -1));

        jPanel2.setBackground(new java.awt.Color(9, 83, 74));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 477, 541, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 15, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(jPanel1.getBackground());
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("ID");
        txtId.setBorder(null);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, -1));

        txtUsername.setBackground(jPanel1.getBackground());
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("Username");
        txtUsername.setBorder(null);
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 122, 195, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 148, 195, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 148, 195, 10));

        txtPassword.setBackground(jPanel1.getBackground());
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Password");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 122, 195, 20));

        txtAlamat.setBackground(jPanel1.getBackground());
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setText("Alamat");
        txtAlamat.setBorder(null);
        txtAlamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlamatMouseClicked(evt);
            }
        });
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 211, 439, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 237, 439, 10));

        txtNama.setBackground(jPanel1.getBackground());
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Nama");
        txtNama.setBorder(null);
        txtNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNamaMouseClicked(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 164, 195, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 190, 439, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 284, 195, 10));

        txtEmail.setBackground(jPanel1.getBackground());
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 258, 195, 20));

        RButTetap.setBackground(jPanel1.getBackground());
        Status.add(RButTetap);
        RButTetap.setForeground(new java.awt.Color(255, 255, 255));
        RButTetap.setSelected(true);
        RButTetap.setText("Tetap");
        jPanel1.add(RButTetap, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 312, -1, -1));

        RButHonorer.setBackground(jPanel1.getBackground());
        Status.add(RButHonorer);
        RButHonorer.setForeground(new java.awt.Color(255, 255, 255));
        RButHonorer.setText("Honorer");
        jPanel1.add(RButHonorer, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 338, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 312, -1, -1));

        txtUmur.setBackground(jPanel1.getBackground());
        txtUmur.setForeground(new java.awt.Color(255, 255, 255));
        txtUmur.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUmur.setText("Umur");
        txtUmur.setBorder(null);
        txtUmur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUmurMouseClicked(evt);
            }
        });
        jPanel1.add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 261, 70, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 284, 70, 10));

        RButPerempuan.setBackground(jPanel1.getBackground());
        JenisKelamin.add(RButPerempuan);
        RButPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        RButPerempuan.setSelected(true);
        RButPerempuan.setText("Perempuan");
        jPanel1.add(RButPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 377, -1, -1));

        RButLaki.setBackground(jPanel1.getBackground());
        JenisKelamin.add(RButLaki);
        RButLaki.setForeground(new java.awt.Color(255, 255, 255));
        RButLaki.setText("Laki-laki");
        jPanel1.add(RButLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 403, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Kelamin");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 381, -1, -1));

        jLabel2.setBackground(jPanel1.getBackground());
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlamatMouseClicked
        // TODO add your handling code here:
        txtAlamat.setText("");
    }//GEN-LAST:event_txtAlamatMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(exit, "Program Dimatikan");
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void btnSubmitRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitRegisterMouseExited
        btnSubmitRegister.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_btnSubmitRegisterMouseExited

    private void btnSubmitRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitRegisterMouseEntered
        btnSubmitRegister.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_btnSubmitRegisterMouseEntered

    private void txtNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaMouseClicked
        // TODO add your handling code here:
        txtNama.setText("");
    }//GEN-LAST:event_txtNamaMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void jbtnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSubmitMouseEntered
        btnSubmitRegister.setBackground(new Color(0,171,143));
    }//GEN-LAST:event_jbtnSubmitMouseEntered

    private void jbtnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSubmitMouseExited
        btnSubmitRegister.setBackground(new Color(0,134,112));
    }//GEN-LAST:event_jbtnSubmitMouseExited

    private void txtUmurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUmurMouseClicked
        txtUmur.setText("");
    }//GEN-LAST:event_txtUmurMouseClicked

    public JRadioButton getRButHonorer() {
        return RButHonorer;
    }

    public JRadioButton getRButLaki() {
        return RButLaki;
    }

    public JRadioButton getRButPerempuan() {
        return RButPerempuan;
    }

    public JRadioButton getRButTetap() {
        return RButTetap;
    }

    public JButton getJbtnSubmit() {
        return jbtnSubmit;
    }

    public JTextField getTxtAlamat() {
        return txtAlamat;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }
    
    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtPassword() {
        return txtPassword;
    }
    
    public JTextField getTxtUmur() {
        return txtUmur;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public PegawaiHonorer BuatPegawaiH(){
        PegawaiHonorer p = new PegawaiHonorer(txtUsername.getText().toString(), txtPassword.getText().toString(), txtId.getText().toString(), txtNama.getText().toString(), Integer.parseInt(txtUmur.getText().toString()), txtAlamat.getText().toString(), txtEmail.getText().toString(), '0', 0, 0);
        if(RButLaki.isSelected()){
            p.setJK('L');
        }
        else
        {
            p.setJK('P');
        }
        return p;
    }
    
    public PegawaiTetap BuatPegawaiT(){
        PegawaiTetap p = new PegawaiTetap(txtUsername.getText().toString(), txtPassword.getText().toString(), txtId.getText().toString(), txtNama.getText().toString(), Integer.parseInt(txtUmur.getText().toString()), txtAlamat.getText().toString(), txtEmail.getText().toString(), '0', 0);
        if(RButLaki.isSelected()){
            p.setJK('L');
        }
        else
        {
            p.setJK('P');
        }
        return p;
    }
    
    public void Reset(){
         txtAlamat.setText("Alamat");
         txtEmail.setText("Email");
         txtId.setText("ID");
         txtUsername.setText("Username");
         txtNama.setText("Nama");
         txtPassword.setText("Password");
         txtUmur.setText("Umur");
         RButHonorer.setSelected(false);
         RButTetap.setSelected(true);
         RButLaki.setSelected(false);
         RButPerempuan.setSelected(true);
    }

    public void addActionListener(ActionListener e){
        jbtnSubmit.addActionListener(e);
        RButHonorer.addActionListener(e);
        RButTetap.addActionListener(e);
        RButPerempuan.addActionListener(e);
        RButLaki.addActionListener(e);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisKelamin;
    private javax.swing.JRadioButton RButHonorer;
    private javax.swing.JRadioButton RButLaki;
    private javax.swing.JRadioButton RButPerempuan;
    private javax.swing.JRadioButton RButTetap;
    private javax.swing.ButtonGroup Status;
    private javax.swing.JPanel btnSubmitRegister;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUmur;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
